name: TerraformConfigration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Name'
        required: true
        type: string
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/{{ github.event.inputs.environment }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login via OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="{{ github.event.inputs.environment }}.tfvars" -var="admin_username=${{ secrets.TF_ADMIN_USERNAME }}" -var="admin_password=${{ secrets.TF_ADMIN_PASSWORD }}"


    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="{{ github.event.inputs.environment }}.tfvars" -var="admin_username=${{ secrets.TF_ADMIN_USERNAME }}" -var="admin_password=${{ secrets.TF_ADMIN_PASSWORD }}"